
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { PetData, ClothingConfig } from "../types";

export type ViewType = 'main' | 'side' | 'back' | 'detail';

export const generatePetPreview = async (
  petData: PetData,
  clothingConfig: ClothingConfig,
  patternBase64?: string,
  humanClothingBase64?: string,
  viewType: ViewType = 'main'
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  const breedDesc = `${petData.breed} (${petData.weight}kg)`;
  const styleDesc = `${clothingConfig.style} made of ${clothingConfig.fabric}`;
  
  // Handle 'Match Reference' case
  const isAutoColor = clothingConfig.color === 'Match Reference';
  const colorDesc = isAutoColor 
    ? "The garment should match the original color palette and tones found in the provided reference images."
    : `The garment has a solid base color of ${clothingConfig.color}.`;
  
  let viewPrompt = "";
  switch(viewType) {
    case 'side': viewPrompt = "Side profile 3D render showing the pet from the left flank."; break;
    case 'back': viewPrompt = "Rear view 3D render showing the pet's back and the clothing's rear fit."; break;
    case 'detail': viewPrompt = "Macro close-up 3D render focusing exclusively on the fabric texture, stitching detail, and the pattern quality."; break;
    default: viewPrompt = "Front 3/4 view standing 3D volumetric render.";
  }

  let prompt = `A highly detailed, professional 3D render of a ${breedDesc}. The pet is wearing a custom-fitted ${styleDesc}. ${colorDesc} ${viewPrompt} `;
  
  if (humanClothingBase64) {
    prompt += "This is a 'Parent-Child Matching' outfit. The design of the pet's clothing MUST perfectly match the human garment shown in the provided reference photo, including its specific pattern, branding, and color palette, while being adapted to the pet's body shape. ";
  } else if (patternBase64) {
    prompt += isAutoColor
      ? "The garment features the pattern and colors directly from the provided pattern image. "
      : `The garment features a pattern applied from the provided pattern image. The pattern is blended naturally with the ${clothingConfig.color} base fabric color. `;
  } else if (!isAutoColor) {
    prompt += `The garment is a solid, elegant ${clothingConfig.color}. `;
  }

  prompt += "High-end octane render style, cinematic lighting, 8k resolution, photorealistic character model aesthetic, studio environment.";

  const parts: any[] = [{ text: prompt }];
  
  if (patternBase64) {
    parts.push({
      inlineData: {
        mimeType: 'image/jpeg',
        data: patternBase64.split(',')[1] || patternBase64
      }
    });
  }

  if (humanClothingBase64) {
    parts.push({
      inlineData: {
        mimeType: 'image/jpeg',
        data: humanClothingBase64.split(',')[1] || humanClothingBase64
      }
    });
  }

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: "1:1"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image was generated by the model.");
  } catch (error: any) {
    console.error(`Gemini API Error (${viewType}):`, error);
    throw new Error(error.message || "Failed to generate preview.");
  }
};
